### ISSUE TITLE
bug (subscription): Initial CTAS queries fail on the backend 

### ISSUE THREAD

**Issue by timoguin** [tiki/core-account-service#332]
# Problem

Currently, the CoreSubscription workflow fails with a LakeFormation permission error when attempting to run CTAS queries that create tables in customer cleanrooms. 

The error:

```
Insufficient Lake Formation permission(s) on s3://mytiki-ocean/cleanroom/ce31b696-bc9d-41b1-b760-b6673c1dfc0f (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: 60a73c23-3b37-454d-b56d-707b9899d2e8; Proxy: null)
```

It appears that the query actually does create the table in that location because it's not empty.

This also causes any subsequent CTAS queries to fail with an error about that location not being empty.

```
ICEBERG_FILESYSTEM_ERROR: Cannot create a table on a non-empty location: s3://mytiki-ocean/cleanroom/ce31b696-bc9d-41b1-b760-b6673c1dfc0f
```

# Fix

The fix is two-pronged:

- Figure out what is broken with the LF permissions on the initial table creation
- Tables should be nested under the base cleanroom location to allow multiple tables to exist in a cleanroom.

There's a draft PR in progress for the second issue: https://github.com/tiki/core-account-service/pull/331

# Other Notes

The Step Functions workflow currently doesn't handle these errors properly, so it just halts the workflow execution and never propagates the error to the API / user. We need to catch these errors instead of failing outright.

**Comment by mike-audi** [comment]
this seems to work now with the multi-table support.
