### ISSUE TITLE
bug (auth): Login page doesn't allow signing out or changing accounts

### ISSUE THREAD

**Issue by timoguin** [tiki/core-account-service#341]
# Problem

Currently, any time I click the login button on the website, I am forced to login to my previously seen account (i.e., via GitHub auth). I would like to login via a different method and/or create a new account. The login page doesn't allow me to do that. The only way I can get it to work is to completely clear all my browsing data or to open a window in private mode.

# Solution

I'm not sure of the right technical approach for this. Need to discuss some ideas with @MiroBenicio and @mike-audi.

# Acceptance Criteria

- [ ] User can select how they want to login (even if they've been previously seen before)

**Comment by mike-audi** [comment]
The logout button should revoke your refresh token which in turn should allow you to login with another method - on the backend if you have the same email on multiple accounts it should already work seamlessly. 

This bug is likely a result of the logout not working correctly.

**Comment by timoguin** [comment]
Confirmed that logout is definitely not clearing tokens or cookies / session storage.

Assigned to @MiroBenicio to investigate.
